# Generated by Django 2.2 on 2022-12-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='open_for_challenge',
            field=models.BooleanField(default=True),
        ),
    ]
