# Generated by Django 2.2 on 2022-12-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdata_open_for_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bio_text',
            field=models.CharField(default="Hi! I'm new here!", max_length=2000),
        ),
    ]
