# Generated by Django 2.2 on 2022-11-18 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_player_is_X', models.BooleanField(default=True)),
                ('first_players_turn', models.BooleanField(default=True)),
                ('open_game', models.BooleanField(default=False)),
                ('game_started', models.BooleanField(default=False)),
                ('game_ended', models.BooleanField(default=False)),
                ('most_recent_move', models.DateTimeField(auto_now_add=True)),
                ('first_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_player_in', to=settings.AUTH_USER_MODEL)),
                ('second_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_player_in', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
