# Generated by Django 2.2 on 2022-11-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='board_string',
            field=models.CharField(default='', max_length=1056),
            preserve_default=False,
        ),
    ]
